-- MySQL Script generated by MySQL Workbench
-- Sat Apr  6 19:49:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gadolandia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gadolandia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gadolandia` DEFAULT CHARACTER SET utf8 ;
USE `gadolandia` ;

-- -----------------------------------------------------
-- Table `gadolandia`.`gado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`gado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `foto` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`descricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`descricao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `altura` FLOAT NOT NULL,
  `peso` FLOAT NULL,
  `cor_olho` VARCHAR(7) NULL,
  `cor_cabelo` VARCHAR(7) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`ilusao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`ilusao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `fotos` JSON NULL,
  `descricao_id` INT NOT NULL,
  `descricao_cor_olhos_id` INT NOT NULL,
  `descricao_cor_cabelo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ilusao_descricao1_idx` (`descricao_id` ASC, `descricao_cor_olhos_id` ASC, `descricao_cor_cabelo_id` ASC) VISIBLE,
  CONSTRAINT `fk_ilusao_descricao1`
    FOREIGN KEY (`descricao_id`)
    REFERENCES `gadolandia`.`descricao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`relacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`relacionamento` (
  `id` VARCHAR(45) NOT NULL,
  `gado_id` INT NOT NULL,
  `ilusao_id` INT NOT NULL,
  `data_inicio` DATETIME NULL,
  `data_fim` DATETIME NULL,
  `status` VARCHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gado_has_ilusao_ilusao1_idx` (`ilusao_id` ASC) VISIBLE,
  INDEX `fk_gado_has_ilusao_gado_idx` (`gado_id` ASC) VISIBLE,
  CONSTRAINT `fk_gado_has_ilusao_gado`
    FOREIGN KEY (`gado_id`)
    REFERENCES `gadolandia`.`gado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gado_has_ilusao_ilusao1`
    FOREIGN KEY (`ilusao_id`)
    REFERENCES `gadolandia`.`ilusao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`estilo_musical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`estilo_musical` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estilo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`cantor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`cantor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`musica` (
  `id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cantor_id` INT NOT NULL,
  `estilo_musical_id` INT NOT NULL,
  `path` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_musica_cantor1_idx` (`cantor_id` ASC) VISIBLE,
  INDEX `fk_musica_estilo_musical1_idx` (`estilo_musical_id` ASC) VISIBLE,
  CONSTRAINT `fk_musica_cantor1`
    FOREIGN KEY (`cantor_id`)
    REFERENCES `gadolandia`.`cantor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_musica_estilo_musical1`
    FOREIGN KEY (`estilo_musical_id`)
    REFERENCES `gadolandia`.`estilo_musical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`descricao_estilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`descricao_estilo` (
  `descricao_id` INT NOT NULL,
  `estilo_musical_id` INT NOT NULL,
  PRIMARY KEY (`descricao_id`, `estilo_musical_id`),
  INDEX `fk_descricao_has_estilo_musical_estilo_musical1_idx` (`estilo_musical_id` ASC) VISIBLE,
  INDEX `fk_descricao_has_estilo_musical_descricao1_idx` (`descricao_id` ASC) VISIBLE,
  CONSTRAINT `fk_descricao_has_estilo_musical_descricao1`
    FOREIGN KEY (`descricao_id`)
    REFERENCES `gadolandia`.`descricao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_descricao_has_estilo_musical_estilo_musical1`
    FOREIGN KEY (`estilo_musical_id`)
    REFERENCES `gadolandia`.`estilo_musical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
