-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 16:27:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gadolandia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gadolandia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gadolandia` DEFAULT CHARACTER SET utf8 ;
USE `gadolandia` ;

-- -----------------------------------------------------
-- Table `gadolandia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`gado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`gado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `apelido` VARCHAR(20) NULL,
  `idade` DATETIME NULL,
  `foto_perfil` VARCHAR(255) NULL,
  `sexo` VARCHAR(1) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gado_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_gado_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `gadolandia`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`estilo_musical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`estilo_musical` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estilo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`cantor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`cantor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_album_cantor1_idx` (`cantor_id` ASC) VISIBLE,
  CONSTRAINT `fk_album_cantor1`
    FOREIGN KEY (`cantor_id`)
    REFERENCES `gadolandia`.`cantor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`musica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `estilo_musical_id` INT NOT NULL,
  `path` VARCHAR(200) NOT NULL,
  `album_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_musica_estilo_musical1_idx` (`estilo_musical_id` ASC) VISIBLE,
  INDEX `fk_musica_album1_idx` (`album_id` ASC) VISIBLE,
  CONSTRAINT `fk_musica_estilo_musical1`
    FOREIGN KEY (`estilo_musical_id`)
    REFERENCES `gadolandia`.`estilo_musical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_musica_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `gadolandia`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`relacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`relacionamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gado_id` INT NOT NULL,
  `ilusao_id` INT NOT NULL,
  `data_inicio` DATETIME NULL,
  `data_fim` DATETIME NULL,
  `status` VARCHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gado_has_gado_gado2_idx` (`ilusao_id` ASC) VISIBLE,
  INDEX `fk_gado_has_gado_gado1_idx` (`gado_id` ASC) VISIBLE,
  CONSTRAINT `fk_gado_has_gado_gado1`
    FOREIGN KEY (`gado_id`)
    REFERENCES `gadolandia`.`gado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gado_has_gado_gado2`
    FOREIGN KEY (`ilusao_id`)
    REFERENCES `gadolandia`.`gado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `biografia` TEXT NULL,
  `altura` FLOAT NULL,
  `peso` FLOAT NULL,
  `sexualidade` VARCHAR(1) NULL,
  `aparencia` JSON NULL,
  `gado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_perfil_gado1_idx` (`gado_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_gado1`
    FOREIGN KEY (`gado_id`)
    REFERENCES `gadolandia`.`gado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`musicas_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`musicas_perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `perfil_id` INT NOT NULL,
  `musica_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_perfil_has_musica_musica1_idx` (`musica_id` ASC) VISIBLE,
  INDEX `fk_perfil_has_musica_perfil1_idx` (`perfil_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_has_musica_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `gadolandia`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_has_musica_musica1`
    FOREIGN KEY (`musica_id`)
    REFERENCES `gadolandia`.`musica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`chatbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`chatbox` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nao_lidas` INT NULL,
  `status` INT NULL,
  `last_login` DATETIME NULL,
  `gado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chatbox_gado1_idx` (`gado_id` ASC) VISIBLE,
  CONSTRAINT `fk_chatbox_gado1`
    FOREIGN KEY (`gado_id`)
    REFERENCES `gadolandia`.`gado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`anexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`anexo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL,
  `path` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`mensagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  `data_envio` DATETIME NULL,
  `anexo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mensagem_anexo1_idx` (`anexo_id` ASC) VISIBLE,
  CONSTRAINT `fk_mensagem_anexo1`
    FOREIGN KEY (`anexo_id`)
    REFERENCES `gadolandia`.`anexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`caixa_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`caixa_entrada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chatbox_id` INT NOT NULL,
  `mensagem_id` INT NOT NULL,
  `data_visualizacao` DATETIME NULL,
  `status` VARCHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chatbox_has_mensagem_mensagem1_idx` (`mensagem_id` ASC) VISIBLE,
  INDEX `fk_chatbox_has_mensagem_chatbox1_idx` (`chatbox_id` ASC) VISIBLE,
  CONSTRAINT `fk_chatbox_has_mensagem_chatbox1`
    FOREIGN KEY (`chatbox_id`)
    REFERENCES `gadolandia`.`chatbox` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chatbox_has_mensagem_mensagem1`
    FOREIGN KEY (`mensagem_id`)
    REFERENCES `gadolandia`.`mensagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gadolandia`.`blocklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gadolandia`.`blocklist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gado_id` INT NOT NULL,
  `chatbox_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_blocklist_gado1_idx` (`gado_id` ASC) VISIBLE,
  INDEX `fk_blocklist_chatbox1_idx` (`chatbox_id` ASC) VISIBLE,
  CONSTRAINT `fk_blocklist_gado1`
    FOREIGN KEY (`gado_id`)
    REFERENCES `gadolandia`.`gado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blocklist_chatbox1`
    FOREIGN KEY (`chatbox_id`)
    REFERENCES `gadolandia`.`chatbox` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
